# Use root/example as user/password credentials
version: '3.1'

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
    - "27017:27017"
  postgresql:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: test